apiVersion: v1
kind: Service
metadata:
  name: limonero
spec:
  type: ClusterIP
  ports: 
  - port: 23402
  selector:
    app: limonero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limonero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limonero
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: limonero
    spec:
      containers:
      - image: eubraatmosphere/eubraatmosphere_autobuild:ub16_limonero_sshfsclient
        imagePullPolicy: Always
        name: limonero
        volumeMounts:
        - name: "limonero-config"
          mountPath: /usr/local/limonero/conf/limonero-config.yaml
          subPath: limonero-config.yaml
        - name: hdfs-pvc
          mountPath: /srv/storage/
        env:
          - name: SSHPRIVKEY
            valueFrom:
              secretKeyRef:
                name: sshfs-secret
                key: sshprivkey
          - name: SSHPUBKEY
            valueFrom:
              secretKeyRef:
                name: sshfs-secret
                key: sshpubkey
          - name: SERVER
            valueFrom:
              configMapKeyRef:
                name: sshfs-configmap
                key: server
          - name: MOUNTPOINT
            valueFrom:
              configMapKeyRef:
                name: sshfs-configmap
                key: mountpoint
      restartPolicy: Always
      volumes:
      - name: "limonero-config"
        configMap:
          name: "limonero-config"
      - name: hdfs-pvc
        persistentVolumeClaim:
          claimName: hdfs-pvc

