apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-${NAMESPACE}-pv2
  labels:
    type: local
spec:
  capacity:
    storage: 100Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ${STORAGE_PATH}/${NAMESPACE}/mysql-data
