apiVersion: apps/v1
kind: Deployment
metadata:
  name: seed-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seed-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seed-worker
    spec:
      containers:
      - image: 150.164.203.230:5000/eubrabigsea/seed:latest
        imagePullPolicy: Always
        name: seed-worker
        command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/entrypoint", "worker"]
        volumeMounts:
        - name: "seed-config"
          mountPath: /usr/local/seed/conf/seed-config.yaml
          subPath: seed-config.yaml
      restartPolicy: Always
      volumes:
      - name: "seed-config"
        configMap:
          name: "seed-config"
 
