apiVersion: v1
kind: Service
metadata:
  name: seed
spec:
  type: ClusterIP
  ports: 
  - port: 23405
  selector:
    app: seed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: seed
    spec:
      containers:
      - image: 150.164.203.230:5000/eubrabigsea/seed:latest
        imagePullPolicy: IfNotPresent 
        name: seed
        volumeMounts:
        - name: "seed-config"
          mountPath: /usr/local/seed/conf/seed-config.yaml
          subPath: seed-config.yaml
      restartPolicy: Always
      volumes:
      - name: "seed-config"
        configMap:
          name: "seed-config"
 
