apiVersion: apps/v1
kind: Deployment
metadata:
  name: thorn-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thorn-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thorn-worker
    spec:
      containers:
      - image: eubrabigsea/thorn:latest
        imagePullPolicy: IfNotPresent 
        name: thorn-worker
        command: ["/usr/bin/dumb-init", "--", "/usr/local/bin/entrypoint", "worker"]
        volumeMounts:
        - name: "thorn-config"
          mountPath: /usr/local/thorn/conf/thorn-config.yaml
          subPath: thorn-config.yaml
      restartPolicy: Always
      volumes:
      - name: "thorn-config"
        configMap:
          name: "thorn-config"
 
