apiVersion: v1
kind: Service
metadata:
  name: thorn
spec:
  type: ClusterIP
  ports: 
  - port: 23400
  selector:
    app: thorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thorn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: thorn
    spec:
      containers:
      - image: eubrabigsea/thorn:latest
        imagePullPolicy: IfNotPresent 
        name: thorn
        volumeMounts:
        - name: "thorn-config"
          mountPath: /usr/local/thorn/conf/thorn-config.yaml
          subPath: thorn-config.yaml
      restartPolicy: Always
      volumes:
      - name: "thorn-config"
        configMap:
          name: "thorn-config"
 
