# Caipirinha configuration file
caipirinha:
    debug: false
    environment: prod
    port: 23401
    storage_id: 2
    secret: ${AUTH_TOKEN}
    servers:
        database_url: mysql+pymysql://root:lemon@mysql/caipirinha?charset=utf8
    services:
    config:
        SQLALCHEMY_POOL_SIZE: 0
        SQLALCHEMY_POOL_RECYCLE: 60

