# Seed configuration file
seed:
    debug: false
    environment: prod
    port: 23405
    secret: ${AUTH_TOKEN}
    deployment_port_range: [35000-39999]
    servers:
        database_url: mysql+pymysql://root:lemon@mysql/seed?charset=utf8
        redis_url: redis://redis:6379
    services:
        thorn:
            url: http://thorn:3000
            token: '${AUTH_TOKEN}'
    config:
        SQLALCHEMY_POOL_SIZE: 100
        SQLALCHEMY_POOL_RECYCLE: 600
